# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 11:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerCategoryWeighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weighting', models.FloatField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaQuizbot.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='ApproachCultureCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DidYouKnowQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=256)),
                ('approach_culture', models.ManyToManyField(blank=True, to='operaQuizbot.ApproachCultureCategory')),
            ],
        ),
        migrations.CreateModel(
            name='FacebookPage',
            fields=[
                ('facebook_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Facebook Page',
            },
        ),
        migrations.CreateModel(
            name='FinancialCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='OperaCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='OperaGoerCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('opera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaQuizbot.Opera')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('facebook_psid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('approach_culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaQuizbot.ApproachCultureCategory')),
                ('financial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaQuizbot.FinancialCategory')),
                ('likes', models.ManyToManyField(to='operaQuizbot.FacebookPage', verbose_name='Facebook Likes')),
                ('opera_goer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaQuizbot.OperaGoerCategory')),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=128)),
                ('next_question', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='operaQuizbot.Question')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedMessage',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaQuizbot.Answer')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaQuizbot.Profile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaQuizbot.Question')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='recorded_answers',
            field=models.ManyToManyField(through='operaQuizbot.UserAnswer', to='operaQuizbot.Question'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opera',
            name='categories',
            field=models.ManyToManyField(to='operaQuizbot.OperaCategory'),
        ),
        migrations.AddField(
            model_name='facebookpage',
            name='categories',
            field=models.ManyToManyField(to='operaQuizbot.OperaCategory'),
        ),
        migrations.AddField(
            model_name='didyouknowquestion',
            name='financial',
            field=models.ManyToManyField(blank=True, to='operaQuizbot.FinancialCategory'),
        ),
        migrations.AddField(
            model_name='didyouknowquestion',
            name='opera_goer',
            field=models.ManyToManyField(blank=True, to='operaQuizbot.OperaGoerCategory'),
        ),
        migrations.AddField(
            model_name='answercategoryweighting',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaQuizbot.OperaCategory'),
        ),
        migrations.AddField(
            model_name='answer',
            name='categories',
            field=models.ManyToManyField(through='operaQuizbot.AnswerCategoryWeighting', to='operaQuizbot.OperaCategory'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaQuizbot.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together=set([('question', 'profile')]),
        ),
    ]
