# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaQuizbot', '0002_auto_20171201_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='did_you_know',
            field=models.ManyToManyField(blank=True, to='operaQuizbot.DidYouKnowQuestion'),
        ),
    ]
