# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaQuizbot', '0004_auto_20171201_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='opera',
            name='url',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
